package io.mindspice.simplypages.components;

import io.mindspice.simplypages.core.Component;

/**
 * Renders trusted HTML without escaping.
 * Use only with content generated by the framework or other trusted sources.
 */
public class RawHtml implements Component {
    private final String html;

    public RawHtml(String html) {
        this.html = html == null ? "" : html;
    }

    public static RawHtml create(String html) {
        return new RawHtml(html);
    }

    @Override
    public String render() {
        return html;
    }
}
